version: "3"

networks:
  devops:
    external: false

volumes:
  postgres-s3:
    driver: local
  gitea-s3:
    driver: local
  code-s3:
    driver: local

services:
  server:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - USER_UID=$USER_UID
      - USER_GID=$USER_GID
      - GITEA__database__DB_TYPE=$GITEA__database__DB_TYPE
      - GITEA__database__HOST=$GITEA__database__HOST
      - GITEA__database__NAME=$GITEA__database__NAME
      - GITEA__database__USER=$GITEA__database__USER
      - GITEA__database__PASSWD=$GITEA__database__PASSWD
    restart: always
    networks:
      - devops
    volumes:
      - gitea-s3:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8888:3000"
      - "2221:22"
    depends_on:
       - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - devops
    volumes:
      - postgres-s3:/var/lib/postgresql/data
  code:
    image: linuxserver/code-server:4.7.0
    container_name: code-server
    environment:
      - PUID=$USER_UID
      - PGID=$USER_GID
      - TZ=Europe/Oslo
      - PASSWORD=$PASSWORD #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=$PASSWORD #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    restart: always
    networks:
      - devops
    volumes:
      - code-s3:/config
    ports:
      - "8443:8443"
    depends_on:
       - db
