version: "3"

networks:
  proxy:
    external: true
  trunk:
    external: true
  secure:
    external: true

volumes:
  postgres-s3:
    driver: local
  gitea-s3:
    driver: local
  code-s3:
    driver: local
  wikijs_data:
    driver: local
  wikijs_config:
    driver: local
  appflowy-data:
    driver: local

services:
  server:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - USER_UID=$USER_UID
      - USER_GID=$USER_GID
      - GITEA__database__DB_TYPE=$GITEA__database__DB_TYPE
      - GITEA__database__HOST=$GITEA__database__HOST
      - GITEA__database__NAME=$GITEA__database__NAME
      - GITEA__database__USER=$GITEA__database__USER
      - GITEA__database__PASSWD=$GITEA__database__PASSWD
    restart: always
    labels:
      traefik.enable: true
      traefik.http.router.gitea.endpoints:
      traefik.http.router.gitea.rule: "Host(`git.vrl.sh`)"
      traefik.http.routers.gitea.tls: true
      traefik.http.routers.gitea.tls.certresolver: "staging"
    networks:
      - proxy
      - trunk
    volumes:
      - gitea-s3:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
       - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - trunk
    volumes:
      - postgres-s3:/var/lib/postgresql/data
  code:
    image: linuxserver/code-server:4.7.0
    container_name: code-server
    environment:
      - PUID=$USER_UID
      - PGID=$USER_GID
      - TZ=$TZ
      - PASSWORD=$PASSWORD #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=$PASSWORD #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    restart: always
    labels:
      traefik.enable: true
      traefik.http.router.code.endpoints:
      traefik.http.router.code.rule: "Host(`code.vrl.sh`)"
      traefik.http.routers.code.tls: true
      traefik.http.routers.code.tls.certresolver: "staging"
    networks:
      - proxy
    volumes:
      - code-s3:/config
    ports:
      - "8443:8443"
    depends_on:
       - db

  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    networks:
      - secure
    environment:
      - PUID=$USER_UID
      - PGID=$USER_GID
      - TZ=$TZ
    volumes:
      - wikijs_config:/config
      - wikijs_data:/data
    restart: unless-stopped
